# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67d6c2937db7d43aec25844ec49bb3c983aeb725c9578bdd0225b32bc07b4bef382a779e9d9a981b38de2c0ad1d61a090581bf7c673334d895ff7d89972132d0

test:
  secret_key_base: 2609d2ff502b54e26ec46499c3fae66467ebaba82efe74f5f0d339dc0e26c83b75c85b6a6e0d98584a6ec4c7d10fdf6f3365a9f263b193665b2f7c630ca25fc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
