# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc78e6d909523b2f106c39dd1bd4e3d9124c69f54b62bbaaaa93cc9a273e9efaa090fb8f93eb7dd89f4426530c31404be35b98662a678c43204c53ef44a3fce0

test:
  secret_key_base: de014d6b2877011056b06c2aafb0ab3aaae796607026bb2bf713c7e2636afbc527d72d1e289505421bc48cf368bf1015d06f9f921793ace213b64f7989426468

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
