# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 446e02e120ac7ea12d932d15abfd4776d9121644698d10cadb48b12d903c5f48ed4980285a9a18d69c4388e08c7c52299d172342b483f8aeaf24afbca3309bda

test:
  secret_key_base: 5fc67ad420ab4b54f33483147a9c24152c904741462bc898d8a587255610deb21b0f6e6af6d9ffea7d837a93c5e1d9d2fbdea9d66120a9ee415ea29a5c89c342

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
